papiSMS/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
urlpatterns = [
	
	url(r'^$', views.ColegioIndex, name='ColegioIndex'),
	url(r'^send/(?P<tipo>[a-z]+)/(?P<dat>.+)*$', views.Send, name='Send'),
	url(r'^colegios/(?P<colegio_id>[0-9]+)/$', views.ColegioDetail, name='ColegioDetail'),
	url(r'^colegios/(?P<colegio_id>[0-9]+)/cursos/(?P<curso_id>[0-9]+)/$', views.CursoDetail, name='CursoDetail'),
	url(r'^colegios/(?P<colegio_id>[0-9]+)/cursos/(?P<curso_id>[0-9]+)/alumnos/(?P<alumno_id>[0-9]+)$', views.AlumnoDetail, name='AlumnoDetail'),

] 

papinotas/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^accounts/login/autenticar$', views.autenticar, name="autenticar"),
	url(r'^accounts/login/$', auth_views.login),
    url(r'^pony$', views.pony),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^papiSMS/', include('papiSMS.urls', namespace="papiSMS")),
    url(r'^$', include('papiSMS.urls', namespace="papiSMS")),


]

papiSMS/models.py
from django.db import models

# Create your models here.

class Colegio(models.Model):
    nombre = models.CharField(max_length=200)
		
    

class Curso(models.Model):
    nombre = models.CharField(max_length=200)
    colegio = models.ForeignKey(Colegio)
    colegio.db_column='colegio'
		    

class Alumno(models.Model):
    nombre = models.CharField(max_length=200)
    numero = models.CharField(max_length=200)
    curso = models.ForeignKey(Curso)
    curso.db_column='curso'

papiSMS/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from .models import *
from django.template.context_processors import csrf
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
import requests
# Create your views here.

@login_required
def Send(request,tipo,dat):
	if(request.POST):
		ls=[]
		i=1

		alum= [x.split("_")[1]for x in request.POST if "user_" in x] #kawaii
		for e in alum:
			us=Alumno.objects.get(pk=e)
			ls.append({"Mobile":us.numero, "Message":request.POST['content']})

		payload = {'username': 'papitest5', 'password': 'clavetest2','data':json.dumps(ls)}
		headers = {'content-type': 'application/x-www-form-urlencoded'}
		r = requests.post("http://52.3.188.254/Send.php", headers=headers,data=payload)
		return HttpResponse(r)

	else:

		if(tipo=="colegio"):
			cursos=Curso.objects.filter(colegio=dat)
		elif(tipo=="curso"):
			cursos=Curso.objects.filter(pk=dat)
		else:
			curso=Alumno.objects.get(pk=dat)
		
		if(tipo!="alumno"):
			res=[]
			for e in cursos:
				res+=Alumno.objects.filter(curso=e)
			return render(request, 'papiSMS/send.html', {'data':res})
		else:
			
			return render(request, 'papiSMS/send.html', {'data':[curso]})
			
@login_required	
def ColegioIndex(request):
	if request.user.is_authenticated():
		colegios_list = Colegio.objects.all()
		context = {'colegios_list': colegios_list}
		return render(request, 'papiSMS/colegios_index.html', context)

@login_required
def ColegioDetail(request,colegio_id):
	cursos_list = Curso.objects.filter(colegio=colegio_id)
	context = {'cursos_list': cursos_list}
	return render(request, 'papiSMS/colegios_detail.html', context)

@login_required
def CursoDetail(request,colegio_id,curso_id):
	alumnos_list = Alumno.objects.filter(curso=curso_id)
	context = {'alumnos_list': alumnos_list}
	return render(request, 'papiSMS/cursos_detail.html', context)

@login_required
def AlumnoDetail(request,colegio_id,curso_id,alumno_id):
	context = {'alumno': Alumno.objects.get(id=alumno_id)}
	return render(request, 'papiSMS/alumnos_detail.html', context)	

papinotas/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
# Create your views here.

def autenticar(request):
	if request.POST:
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
		    if user.is_active:
		        login(request, user)
		        return HttpResponseRedirect(request.GET.get('next','/papiSMS'))
		        # Redirect to a success page.
		    else:
		        # Return a 'disabled account' error message
		       return ""
		else:
			return ""
def pony(request):
	if(request.GET):
		return  HttpResponse(request.GET)

papiSMS/templates/papiSMS/alumnos_detail.html
<a href="{% url 'papiSMS:Send' 'alumno' alumno.id %}"> <h1>Enviar Mensaje</h1> </a>
<h1>{{ alumno.nombre }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

papiSMS/templates/papiSMS/colegios_detail.html
<a href="{% url 'papiSMS:Send' 'colegio' cursos_list.first.colegio.id %}"> <h1>Enviar Mensaje al Colegio</h1> </a>
{% if cursos_list %}
    <ul>
    {% for curso in cursos_list %}

        <li><a href="{% url 'papiSMS:CursoDetail' curso.colegio.id curso.id %}">{{ curso.nombre }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay cursos para mostrar.</p>
{% endif %}

papiSMS/templates/papiSMS/colegios_index.html
<h1>Colegios: </h1>
{% if colegios_list %}
    <ul>
    {% for colegio in colegios_list %}
        <li><a href="{% url 'papiSMS:ColegioDetail' colegio.id %}">{{ colegio.nombre }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay colegios para mostrar.</p>
{% endif %}

papiSMS/templates/papiSMS/cursos_detail.html
<a href="{% url 'papiSMS:Send' 'curso' alumnos_list.first.curso.id %}"> <h1>Enviar Mensaje al Curso</h1> </a>
{% if alumnos_list %}
    <ul>
    {% for alumno in alumnos_list %}
        <li><a href="{% url 'papiSMS:AlumnoDetail' alumno.curso.colegio.id alumno.curso.id alumno.id %}">{{ alumno.nombre }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay alumnos para mostrar.</p>
{% endif %}

papiSMS/templates/papiSMS/send.html
<form method="post" action=".">
	{% csrf_token %}
	{% if data %}
	    <ul>
	    {% for alumno in data %}

	        <li>{{alumno.nombre}} {{alumno.numero}} <input type='checkbox' name='user_{{alumno.id}}' checked />
	        </li> 

	    {% endfor %}
	    </ul>
	{% else %}
	    <p>No hay alumnos para mostrar.</p>
	{% endif %}

	<input type="textarea" name='content'/>

	<input type="submit"/>

</form>